// @ts-check
// ESLint flat config — activated in T-23 (ESLint 8 → 9), migrated in T-39 (ESLint 9 → 10).
// Plugins:
//   eslint                                  10.x
//   @eslint/js                              10.x
//   @typescript-eslint/eslint-plugin        8.x     (flat/recommended)
//   @typescript-eslint/parser               8.x
//   eslint-plugin-astro                     3.x     (recommended, jsx-a11y-recommended)
//   eslint-plugin-jsx-a11y-x                0.x     (used internally by astro a11y rules)
//   astro-eslint-parser                     3.x     (@astrojs/compiler-rs)

import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import astroPlugin from 'eslint-plugin-astro';

export default [
  // -------------------------------------------------------------------------
  // Global ignores — migrated from .eslintignore (ESLint 9 no longer reads it)
  // and from legacy ignorePatterns.
  //
  // public/ contains browser scripts (toggle-theme.js) that use global browser
  // APIs; these were never linted under the legacy config (.eslintignore had
  // `public`). Continuing to ignore to preserve baseline behaviour.
  //
  // src/env.d.ts is auto-generated by Astro on every `astro sync`; it uses
  // a triple-slash reference that @typescript-eslint/triple-slash-reference
  // flags. Since it's a generated file that must not be modified, we ignore it.
  // -------------------------------------------------------------------------
  {
    ignores: [
      'dist/',
      '.astro/',
      'node_modules/',
      '.husky/',
      '.vscode/',
      'public/',
      'docs/library-packages-upgrade/baseline/',
      'src/env.d.ts',
    ],
  },

  // -------------------------------------------------------------------------
  // Block 1 — eslint:recommended for all JS/TS source files
  // -------------------------------------------------------------------------
  {
    files: ['**/*.{js,mjs,cjs,jsx,ts,tsx}'],
    rules: {
      ...js.configs.recommended.rules,
    },
  },

  // -------------------------------------------------------------------------
  // Block 2 — TypeScript plugin (flat/recommended) for all JS/TS files
  //
  // @typescript-eslint v8 flat/recommended is an array of config objects:
  //   [0] name + plugins
  //   [1] eslint-recommended overrides (disables core rules TypeScript handles)
  //   [2] @typescript-eslint/* recommended rules
  //
  // We spread all entries from the array so parser, plugins, and rules are
  // all applied in the correct order.
  // -------------------------------------------------------------------------
  // TS 6: tsPlugin.configs type says ClassicConfig.Config, but at runtime
  // 'flat/recommended' is a FlatConfig.ConfigArray. Cast to avoid iterator error.
  .../** @type {import('@typescript-eslint/utils').TSESLint.FlatConfig.ConfigArray} */ (tsPlugin.configs['flat/recommended']),

  // -------------------------------------------------------------------------
  // Block 3 — Astro recommended + jsx-a11y-recommended
  //
  // eslint-plugin-astro v2+ is ESM-only and exposes unprefixed preset names.
  // v3 dropped astro/no-omitted-end-tags and astro/valid-compile from
  // recommended — the Rust compiler and `astro check` now cover both.
  // jsx-a11y rules resolve eslint-plugin-jsx-a11y-x (eslint-plugin-jsx-a11y
  // stops at ESLint 9).
  // -------------------------------------------------------------------------
  ...astroPlugin.configs.recommended,
  ...astroPlugin.configs['jsx-a11y-recommended'],
];
