// @ts-check
// ESLint flat config — activated in T-23 (ESLint 8 → 9).
// Drafted in T-12 (hand-expansion of legacy rules under ESLint 8).
// Rewritten in T-23 to use flat-config-native presets from upgraded plugins:
//   eslint                                  9.39.4
//   @eslint/js                              9.39.4
//   @typescript-eslint/eslint-plugin        8.59.1  (flat/recommended)
//   @typescript-eslint/parser               8.59.1
//   eslint-plugin-astro                     1.7.0   (flat/recommended, flat/jsx-a11y-recommended)
//   eslint-plugin-jsx-a11y                  6.10.2
//   astro-eslint-parser                     1.4.0

import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import astroPlugin from 'eslint-plugin-astro';

export default [
  // -------------------------------------------------------------------------
  // Global ignores — migrated from .eslintignore (ESLint 9 no longer reads it)
  // and from legacy ignorePatterns.
  //
  // public/ contains browser scripts (toggle-theme.js) that use global browser
  // APIs; these were never linted under the legacy config (.eslintignore had
  // `public`). Continuing to ignore to preserve baseline behaviour.
  //
  // src/env.d.ts is auto-generated by Astro on every `astro sync`; it uses
  // a triple-slash reference that @typescript-eslint/triple-slash-reference
  // flags. Since it's a generated file that must not be modified, we ignore it.
  // -------------------------------------------------------------------------
  {
    ignores: [
      'dist/',
      '.astro/',
      'node_modules/',
      '.husky/',
      '.vscode/',
      'public/',
      'docs/library-packages-upgrade/baseline/',
      'src/env.d.ts',
    ],
  },

  // -------------------------------------------------------------------------
  // Block 1 — eslint:recommended for all JS/TS source files
  // -------------------------------------------------------------------------
  {
    files: ['**/*.{js,mjs,cjs,jsx,ts,tsx}'],
    rules: {
      ...js.configs.recommended.rules,
    },
  },

  // -------------------------------------------------------------------------
  // Block 2 — TypeScript plugin (flat/recommended) for all JS/TS files
  //
  // @typescript-eslint v8 flat/recommended is an array of config objects:
  //   [0] name + plugins
  //   [1] eslint-recommended overrides (disables core rules TypeScript handles)
  //   [2] @typescript-eslint/* recommended rules
  //
  // We spread all entries from the array so parser, plugins, and rules are
  // all applied in the correct order.
  // -------------------------------------------------------------------------
  ...tsPlugin.configs['flat/recommended'],

  // -------------------------------------------------------------------------
  // Block 3 — Astro flat/recommended + flat/jsx-a11y-recommended
  //
  // eslint-plugin-astro v1 ships flat-config-native presets that include:
  //   - plugin registration
  //   - astro-eslint-parser + tsParser wiring (languageOptions)
  //   - processor registration (for inline <script> blocks)
  //   - astro/* rules
  // Spreading both arrays handles everything that Block 3b manually did in T-12.
  // -------------------------------------------------------------------------
  ...astroPlugin.configs['flat/recommended'],
  ...astroPlugin.configs['flat/jsx-a11y-recommended'],
];
